"""Added due_date and priority to Task

Revision ID: 7c7b14dbc413
Revises: 6b0cac6f6a7a
Create Date: 2025-02-24 13:39:19.924752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7b14dbc413'
down_revision = '6b0cac6f6a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_task')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.INTEGER(), nullable=True))

    op.create_table('_alembic_tmp_task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('priority', sa.VARCHAR(length=10), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_task'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
